// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeMvN5gQV7uQ5rsZfexTjkPxEMVrDadYQ',
    appId: '1:112414834945:web:221d2f036c2f298173db00',
    messagingSenderId: '112414834945',
    projectId: 'colorsfunland',
    authDomain: 'colorsfunland.firebaseapp.com',
    storageBucket: 'colorsfunland.firebasestorage.app',
    measurementId: 'G-1HFRL7V9BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEIOWE9djjKS4mA9SQ0tqyLlIw3W0vhok',
    appId: '1:112414834945:android:d8f36f243c288e4873db00',
    messagingSenderId: '112414834945',
    projectId: 'colorsfunland',
    storageBucket: 'colorsfunland.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3rQLyn7V7EWZ7GriIjnfMkb9QkTjzD2A',
    appId: '1:112414834945:ios:4f428aaa1aea75b373db00',
    messagingSenderId: '112414834945',
    projectId: 'colorsfunland',
    storageBucket: 'colorsfunland.firebasestorage.app',
    iosBundleId: 'com.example.colorsFunland',
  );
}