// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu7VVnzhWnpLUgjhevF3eKqVZRFUH6ea8',
    appId: '1:446110723678:web:c7ba6b4b0ad7128cbd4ecf',
    messagingSenderId: '446110723678',
    projectId: 'funcolor-f8bde',
    authDomain: 'funcolor-f8bde.firebaseapp.com',
    storageBucket: 'funcolor-f8bde.firebasestorage.app',
    measurementId: 'G-ZYEPE6NR9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeMnlUr0c1x4OCvjhEwa4975pkYy-j8MU',
    appId: '1:446110723678:android:2e90ada40432216ebd4ecf',
    messagingSenderId: '446110723678',
    projectId: 'funcolor-f8bde',
    storageBucket: 'funcolor-f8bde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9wNatuKaNPwlGH2Fdh53J1s2Pg0ZN7Qo',
    appId: '1:446110723678:ios:3b5a3fbc2ad902f7bd4ecf',
    messagingSenderId: '446110723678',
    projectId: 'funcolor-f8bde',
    storageBucket: 'funcolor-f8bde.firebasestorage.app',
    iosBundleId: 'com.example.colorsFunland',
  );
}
